name: Feature request
description: Suggest an idea or improvement for NexumDB
labels: [enhancement]
title: "feat: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement!

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What problem does this feature solve? What is the desired outcome?
      placeholder: Support SQL JOIN between tables...
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
      placeholder: Add a JOIN operator with nested loop execution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: List any alternative solutions or workarounds you have considered.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, diagrams, or references to existing issues.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
